# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08my.proto\"p\n\x04Time\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\x12\r\n\x05hours\x18\x04 \x01(\x05\x12\x0f\n\x07minutes\x18\x05 \x01(\x05\x12\x0f\n\x07seconds\x18\x06 \x01(\x05\x12\r\n\x05nanos\x18\x07 \x01(\x05\"-\n\tTimestamp\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\"\x9b\x03\n\x03Log\x12\r\n\x05index\x18\x01 \x01(\x03\x12\x13\n\x04time\x18\x02 \x01(\x0b\x32\x05.Time\x12\x1d\n\ttimestamp\x18\x03 \x01(\x0b\x32\n.Timestamp\x12\x19\n\x05\x65\x63uid\x18\x04 \x01(\x0e\x32\n.Log.EcuId\x12\x17\n\x04\x61pid\x18\x05 \x01(\x0e\x32\t.Log.ApId\x12\x17\n\x04\x63tid\x18\x06 \x01(\x0e\x32\t.Log.CtId\x12\x17\n\x04type\x18\x07 \x01(\x0e\x32\t.Log.Type\x12\x0f\n\x07payload\x18\x08 \x01(\t\"%\n\x05\x45\x63uId\x12\x08\n\x04ORIN\x10\x00\x12\t\n\x05\x41URIX\x10\x01\x12\x07\n\x03\x46SI\x10\x02\"8\n\x04\x41pId\x12\x08\n\x04VIOS\x10\x00\x12\x08\n\x04SYSL\x10\x01\x12\x08\n\x04VUig\x10\x02\x12\x08\n\x04VDIS\x10\x03\x12\x08\n\x04VSVS\x10\x04\"$\n\x04\x43tId\x12\x08\n\x04\x63ore\x10\x00\x12\x08\n\x04sysl\x10\x01\x12\x08\n\x04vuig\x10\x02\"S\n\x04Type\x12\x0b\n\x07\x64\x65\x66\x61ult\x10\x00\x12\x07\n\x03off\x10\x01\x12\t\n\x05\x65rror\x10\x02\x12\x08\n\x04warn\x10\x03\x12\x08\n\x04info\x10\x04\x12\t\n\x05\x64\x65\x62ug\x10\x05\x12\x0b\n\x07verbose\x10\x06\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIME._serialized_start=12
  _TIME._serialized_end=124
  _TIMESTAMP._serialized_start=126
  _TIMESTAMP._serialized_end=171
  _LOG._serialized_start=174
  _LOG._serialized_end=585
  _LOG_ECUID._serialized_start=367
  _LOG_ECUID._serialized_end=404
  _LOG_APID._serialized_start=406
  _LOG_APID._serialized_end=462
  _LOG_CTID._serialized_start=464
  _LOG_CTID._serialized_end=500
  _LOG_TYPE._serialized_start=502
  _LOG_TYPE._serialized_end=585
# @@protoc_insertion_point(module_scope)
